# Generated by Django 5.1.4 on 2025-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactus_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram',
            field=models.CharField(blank=True, default='https://instagram.com/username', max_length=250, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram',
            field=models.CharField(blank=True, default='https://t.me/username', max_length=250, null=True, verbose_name='لینک تلگرام'),
        ),
    ]
