# Generated by Django 5.1.4 on 2025-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_comment_body_alter_comment_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
    ]
