# Generated by Django 5.1.4 on 2025-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='متا دیسکریپشن'),
        ),
    ]
