# Generated by Django 5.1.4 on 2025-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_alt_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
    ]
