# Generated by Django 5.1.4 on 2025-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وب سایت'),
        ),
    ]
