# Generated by Django 5.1.4 on 2025-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
    ]
