# Generated by Django 5.1.4 on 2025-04-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='متا دیسکریپشن'),
        ),
    ]
